// Generated by CoffeeScript 1.9.2
(function() {
  var async, collectionName, connection, env, mongoose, mountains;

  env = process.env.NODE_ENV || 'dev';

  console.log(env + ' mode');

  collectionName = env === 'production' ? 'forecasts' : 'forecast_devs';

  async = require('async');

  mongoose = require('mongoose');

  mountains = require('../../res/mountains.json');

  mongoose.connect('mongodb://yes:yes@ds035280.mongolab.com:35280/hiking');

  connection = mongoose.connection;

  connection.on('error', console.error.bind(console, 'connection error:'));

  connection.once('open', function(callback) {
    return async.series({
      dropCollection: function(callback) {
        return connection.db.dropCollection(collectionName, function(err, result) {
          return callback(err, result);
        });
      },
      createCollection: function(callback) {
        return connection.db.createCollection(collectionName, function(err, result) {
          return callback(err, result);
        });
      },
      insertDocuments: function(callback) {
        return connection.db.collection(collectionName).insert(mountains, function(err, result) {
          return callback(err, result);
        });
      }
    }, function(err, results) {
      if (err) {
        console.log('err: ' + err);
      } else {
        console.log('done');
      }
      return process.exit();
    });
  });

}).call(this);
